id: A45D9A8D8
title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and Mahā
  Ati'
type: translation
pechas:
- I3162CFC1
- IE3EF434D
- I99ABAF5F
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:35:31.946248
  last_modified_at: 2023-01-04 11:35:31.946261
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I3162CFC1/8551: 3AE8
  IE3EF434D/0E89: 3AE8
  I99ABAF5F/45D9: 3AE8
